/**
 * Constants and translations for the AI Tests feature.
 */

export const SUBJECTS = [
    { id: 'math', name: 'Mathematics', icon: '📐' },
    { id: 'biology', name: 'Biology', icon: '🧬' },
    { id: 'chemistry', name: 'Chemistry', icon: '⚗️' },
    { id: 'physics', name: 'Physics', icon: '⚛️' },
    { id: 'history', name: 'History', icon: '🏛️' },
    { id: 'cs', name: 'Comp Sci', icon: '💻' },
    { id: 'lit', name: 'Literature', icon: '📚' },
    { id: 'geo', name: 'Geography', icon: '🌍' },
];

export const LANGUAGES = [
    { id: 'es', name: 'Spanish', icon: '🇪🇸' },
    { id: 'fr', name: 'French', icon: '🇫🇷' },
    { id: 'jp', name: 'Japanese', icon: '🇯🇵' },
    { id: 'de', name: 'German', icon: '🇩🇪' },
];

export const EXAMS = [
    { id: 'ielts', name: 'IELTS (English)', icon: '🇬🇧' },
    { id: 'toefl', name: 'TOEFL (English)', icon: '🇺🇸' },
    { id: 'sat_math', name: 'SAT Math', icon: '📝' },
    { id: 'gre_verbal', name: 'GRE Verbal', icon: '🎓' },
    { id: 'nclex', name: 'NCLEX (Nursing)', icon: '🩺' },
];

export const DIFFICULTIES = ['Beginner', 'Intermediate', 'Advanced', 'Expert'];

export const MOCK_TESTS_DATA = [
    { id: 1, title: 'IELTS Mock Test A', date: 'Oct 24', score: 7.5, total: 9.0, status: 'Completed' },
    { id: 2, title: 'Calculus Midterm Prep', date: 'Oct 28', score: 85, total: 100, status: 'Completed' },
    { id: 3, title: 'Intro to Physics', date: 'Nov 02', score: null, total: null, status: 'Upcoming' },
    { id: 4, title: 'TOEFL Reading Section', date: 'Nov 05', score: null, total: null, status: 'Upcoming' },
];

export const TRANSLATIONS = {
    en: {
        myTests: "My Tests", manageExams: "Manage your upcoming exams and build study pathways.",
        aiTutor: "AI Tutor", newExam: "New Exam", nextUp: "Next Up",
        averageScore: "Average Score", completed: "Completed", testsTaken: "Tests taken this year",
        activePathways: "Active Study Pathways", goal: "Goal", examDay: "Exam Day",
        startFullTest: "Start Full Test", recentActivity: "Recent Activity", viewAll: "View All",
        passed: "PASSED", prepare: "Prepare", createStudyPlan: "Create Study Plan",
        subject: "Subject", targetDate: "Target Date", currentLevel: "Current Level",
        topicsToCover: "Topics to Cover",
        topicsPlaceholder: "e.g. Photosynthesis, Cellular Respiration, Genetics...",
        tailorTests: "We'll tailor your practice tests to these topics.",
        generating: "Generating Pathway...", generate: "Generate Pathway",
        sidekick: "Sidekick", aiTestCompanion: "AI Test Companion",
        quickPractice: "Quick Practice", mockExams: "Mock Exams",
        masterSubject: "Master a Subject", aceExam: "Ace Your Exam",
        pickTopic: "Pick a topic and difficulty. I will test your knowledge.",
        simulateExam: "Simulate real exam questions. No hints, standard difficulty.",
        difficulty: "Difficulty", select: "Select",
        startQuiz: "Start Quiz", startMock: "Start Mock",
        generatingContent: "Generating Content", consulting: "Consulting the knowledge base...",
        correct: "Correct!", incorrect: "Incorrect",
        nextQuestion: "Next Question", finishTest: "Finish Test",
        testComplete: "Test Complete!", performance: "Here is how you performed.",
        score: "Score", backHome: "Back to Home",
        connectionError: "Connection Error",
        connectionErrorDesc: "Failed to contact the AI Sidekick. Please check your connection.",
        returnHome: "Return Home", examMode: "Exam Mode", topic: "Topic",
        startPreparation: "Start Preparation", introPhysics: "Intro to Physics",
        mockTest: "Mock Test", practice: "Practice", review: "Review",
        exam: "Exam", target: "Target", vsLastMonth: "vs last month",
        beginner: "Beginner", intermediate: "Intermediate",
        advanced: "Advanced", expert: "Expert",
        Mathematics: "Mathematics", Biology: "Biology", Chemistry: "Chemistry",
        Physics: "Physics", History: "History", "Comp Sci": "Comp Sci",
        Literature: "Literature", Geography: "Geography",
        Spanish: "Spanish", French: "French", Japanese: "Japanese", German: "German",
        "IELTS (English)": "IELTS (English)", "TOEFL (English)": "TOEFL (English)",
        "SAT Math": "SAT Math", "GRE Verbal": "GRE Verbal",
        "NCLEX (Nursing)": "NCLEX (Nursing)", nextUpBadge: "Next Up"
    },
    uz: {
        myTests: "Mening Testlarim", manageExams: "Bo'lajak imtihonlarni boshqaring va o'quv rejasini tuzing.",
        aiTutor: "AI O'qituvchi", newExam: "Yangi Imtihon", nextUp: "Navbatdagi",
        averageScore: "O'rtacha Ball", completed: "Yakunlandi", testsTaken: "Bu yilgi testlar",
        activePathways: "Faol O'quv Rejalari", goal: "Maqsad", examDay: "Imtihon Kuni",
        startFullTest: "To'liq Testni Boshlash", recentActivity: "So'nggi Faoliyat",
        viewAll: "Barchasini Ko'rish", passed: "O'TDI", prepare: "Tayyorlanish",
        createStudyPlan: "O'quv Rejasini Tuzish", subject: "Fan",
        targetDate: "Maqsadli Sana", currentLevel: "Joriy Daraja",
        topicsToCover: "Mavzular", topicsPlaceholder: "Masalan: Fotosintez, Genetika...",
        tailorTests: "Biz testlarni ushbu mavzularga moslashtiramiz.",
        generating: "Reja tuzilmoqda...", generate: "Reja Tuzish",
        sidekick: "Yordamchi", aiTestCompanion: "AI Test Hamrohi",
        quickPractice: "Tezkor Mashq", mockExams: "Sinov Imtihonlari",
        masterSubject: "Fanni O'zlashtirish", aceExam: "Imtihonni Topshirish",
        pickTopic: "Mavzu va qiyinchilikni tanlang. Bilimingizni sinab ko'raman.",
        simulateExam: "Haqiqiy imtihon savollari. Maslahatlar yo'q, standart qiyinchilik.",
        difficulty: "Qiyinchilik", select: "Tanlash",
        startQuiz: "Testni Boshlash", startMock: "Sinovni Boshlash",
        generatingContent: "Mazmun Yaratilmoqda", consulting: "Bilimlar bazasi tekshirilmoqda...",
        correct: "To'g'ri!", incorrect: "Noto'g'ri",
        nextQuestion: "Keyingi Savol", finishTest: "Testni Yakunlash",
        testComplete: "Test Yakunlandi!", performance: "Sizning natijangiz.",
        score: "Ball", backHome: "Bosh Sahifaga",
        connectionError: "Ulanish Xatosi",
        connectionErrorDesc: "AI Yordamchi bilan bog'lanib bo'lmadi. Internetni tekshiring.",
        returnHome: "Qaytish", examMode: "Imtihon Rejimi", topic: "Mavzu",
        startPreparation: "Tayyorgarlikni Boshlash", introPhysics: "Fizikaga Kirish",
        mockTest: "Sinov Testi", practice: "Mashq", review: "Takrorlash",
        exam: "Imtihon", target: "Maqsad", vsLastMonth: "o'tgan oyga nisbatan",
        beginner: "Boshlang'ich", intermediate: "O'rta",
        advanced: "Ilg'or", expert: "Ekspert",
        Mathematics: "Matematika", Biology: "Biologiya", Chemistry: "Kimyo",
        Physics: "Fizika", History: "Tarix", "Comp Sci": "Kompyuter ilmlari",
        Literature: "Adabiyot", Geography: "Geografiya",
        Spanish: "Ispan tili", French: "Fransuz tili", Japanese: "Yapon tili", German: "Nemis tili",
        "IELTS (English)": "IELTS (Ingliz)", "TOEFL (English)": "TOEFL (Ingliz)",
        "SAT Math": "SAT Matematika", "GRE Verbal": "GRE Verbal",
        "NCLEX (Nursing)": "NCLEX (Hamshiralik)", nextUpBadge: "Keyingi"
    },
    ru: {
        myTests: "Мои тесты", manageExams: "Управляйте экзаменами и создавайте учебные планы.",
        aiTutor: "ИИ Репетитор", newExam: "Новый экзамен", nextUp: "Следующий",
        averageScore: "Средний балл", completed: "Завершено", testsTaken: "Тестов за год",
        activePathways: "Активные учебные планы", goal: "Цель", examDay: "День экзамена",
        startFullTest: "Начать полный тест", recentActivity: "Недавняя активность",
        viewAll: "См. все", passed: "СДАЛ", prepare: "Подготовиться",
        createStudyPlan: "Создать план", subject: "Предмет",
        targetDate: "Дата цели", currentLevel: "Текущий уровень",
        topicsToCover: "Темы", topicsPlaceholder: "Например: Фотосинтез, Генетика...",
        tailorTests: "Мы адаптируем тесты под эти темы.",
        generating: "Создание плана...", generate: "Создать план",
        sidekick: "Помощник", aiTestCompanion: "ИИ компаньон по тестам",
        quickPractice: "Быстрая практика", mockExams: "Пробные экзамены",
        masterSubject: "Освоить предмет", aceExam: "Сдать экзамен",
        pickTopic: "Выберите тему и сложность. Я проверю ваши знания.",
        simulateExam: "Симуляция экзамена. Без подсказок, стандартная сложность.",
        difficulty: "Сложность", select: "Выбрать",
        startQuiz: "Начать викторину", startMock: "Начать тест",
        generatingContent: "Генерация контента", consulting: "Обращение к базе знаний...",
        correct: "Верно!", incorrect: "Неверно",
        nextQuestion: "Следующий вопрос", finishTest: "Завершить тест",
        testComplete: "Тест завершен!", performance: "Вот ваши результаты.",
        score: "Очки", backHome: "На главную",
        connectionError: "Ошибка соединения",
        connectionErrorDesc: "Не удалось связаться с ИИ. Проверьте интернет.",
        returnHome: "Вернуться", examMode: "Режим экзамена", topic: "Тема",
        startPreparation: "Начать подготовку", introPhysics: "Введение в физику",
        mockTest: "Пробный тест", practice: "Практика", review: "Обзор",
        exam: "Экзамен", target: "Цель", vsLastMonth: "к прошлому месяцу",
        beginner: "Начинающий", intermediate: "Средний",
        advanced: "Продвинутый", expert: "Эксперт",
        Mathematics: "Математика", Biology: "Биология", Chemistry: "Химия",
        Physics: "Физика", History: "История", "Comp Sci": "Информатика",
        Literature: "Литература", Geography: "География",
        Spanish: "Испанский", French: "Французский", Japanese: "Японский", German: "Немецкий",
        "IELTS (English)": "IELTS (Английский)", "TOEFL (English)": "TOEFL (Английский)",
        "SAT Math": "SAT Математика", "GRE Verbal": "GRE Вербальный",
        "NCLEX (Nursing)": "NCLEX (Медсестринское дело)", nextUpBadge: "Далее"
    }
};
